library(tidyr)
library(stringr)
library(dplyr)
library(jsonlite)


rm(list = ls())
db_dial_skyrim.esm <- read.csv(".\\dbs\\db_DIAL_skyrim.esm.csv")


## DB SHAPING #######################################################################

colnames(db_dial_skyrim.esm)[2] <- "Formid"

## cleaning

db_dial_skyrim.esm <- db_dial_skyrim.esm %>%
  mutate_all(~ na_if(., ""))




db_dial_skyrim.esm_formid_empty <- db_dial_skyrim.esm %>% ## contains QNAM,EDID and FULL but not topic
  filter(is.na(Formid)) %>% ## cleaning
    filter(!is.na(FULL)) ## futher cleaning THIS HAS TO BE REMOVED AT SOME POINT, TO ALLOW ACCEPTFAVOR DIALOGUES


db_dial_skyrim.esm_dist <-  db_dial_skyrim.esm %>% ## contains formids and topics, but not QNAM or EDID
  filter(!is.na(Formid)) %>% ## needed because we already have an empty formid db
    distinct(Formid, .keep_all = TRUE) ## many duplications that have to be cleansed




## need to match EDID from formid_empty with a split version of Topic from dist


db_dial_skyrim.esm_dist_match <- db_dial_skyrim.esm_dist %>%
  mutate(match = str_extract(Topic,"^[^\\[]+")) %>% ## everything that's before first bracket
    mutate(match = str_extract(match, "^[^ ]+")) %>% ## everything that's all together
      filter(!is.na(match)) ## prevent many to many relationships when joining

db_dial_skyrim.esm_formid_empty_match <- db_dial_skyrim.esm_formid_empty %>%
  mutate(match = EDID) %>% ## copy column for join
    filter(!is.na(match)) ## prevent many to many relationships when joining



## Join both
db_dial_skyrim.esm_merged <- full_join(db_dial_skyrim.esm_formid_empty_match, db_dial_skyrim.esm_dist_match, by = "match") %>%
  select_if(~ !all(is.na(.))) ## remove extra columns generated by the join



## db with transformed FULL, and isolated formid cols (ready for extraction)

db_dial_skyrim.esm_json_ready <- db_dial_skyrim.esm_merged %>%
    mutate(
      Formid_isolated = as.character(str_extract_all(Formid.y, "(?<=DIAL:)[^\\]]*")) ## get only formid
    ) %>%
      mutate( ## clasify type of quest
        QNAM_type = case_when(
          str_detect(QNAM.x, "^MQ") ~ "MQ", ## Main Quest
          str_detect(QNAM.x, "^MG") ~ "MG", ## Mages guild
          str_detect(QNAM.x, "^C\\d{2}|CR") ~ "C", ## Companions
          str_detect(QNAM.x, "^DB") ~ "DB", ## Dark brotherhood
          str_detect(QNAM.x, "^CW") ~ "CW", ## Civil war(legion + stormcloacks)
          str_detect(QNAM.x, "^TG") ~ "TG", ## Thieves guild
          str_detect(QNAM.x, "^DA\\d{2}") ~ "DA", ## Daedric
          str_detect(QNAM.x, "^MS\\d{2}|^VC\\d{2}|^dun|^NN\\d{2}|^[Tt]\\d{2}") ~ "MS", ## Side quests
          str_detect(QNAM.x, "Favor|Freeform|Tutorial|BQ|Farm") ~ "misc" ## Miscellaneous INCLUDE CITY DIALOGUE MANUALLY?
        )
      ) %>% ## filter those that didnt have a clear dialogue formid, NA quest (probably cutted content) and match any type of quest
        filter(!is.na(Formid_isolated) & !is.na(QNAM.x) & !is.na(QNAM_type)) %>% 
            mutate(
              FULL_trans = paste0(FULL.x, " (Quest)") ## Add "(Quest)"
            ) %>%
              select(Formid_isolated,FULL_trans,QNAM.x, QNAM_type) ## select cols of interest





################################################################################

## Json generation:

json_gen <- function(db_dial_json_ready,plugin){


  json_obj_list <- vector("list", length(nrow(db_dial_json_ready)))



  for(i in seq_len(nrow(db_dial_json_ready))){

    json_obj_list[[i]] <- { 
     list(
       form_id = paste0(db_dial_json_ready[i,"Formid_isolated"],"|",plugin), 
       type = "DIAL FULL",     
       string = db_dial_json_ready[i,"FULL_trans"]    
     )
   }

   
  }
  
  json_output <- toJSON(json_obj_list, pretty = TRUE, auto_unbox = TRUE)



  return(json_output)

}

json_skyrim.esm <- json_gen(db_dial_skyrim.esm_json_ready,"Skyrim.esm")


write(json_skyrim.esm, ".\\SKSE\\Plugins\\DynamicStringDistributor\\Skyrim.esm\\QuestDialogueTagsSkyrim.esm.json")





